### PR TITLE
Fixups

### PR DESCRIPTION
**Pull request by kernc**
Fixes https://github.com/biolab/orange3-network/issues/23.

### CODE REVIEW

**Comment by BlazZupan** [comment]
Does not work. No selections are shown. In Highligh nodes ... section the selection is set to None, "... given in the ItemSubset" is disabled and associated combo box below it is empty".

**Comment by kernc** [comment]
It works for me. The radio is now enabled by default, but the attribute combo still only populates once the data is present.

**Comment by BlazZupan** [comment]
Selection still does not work. I use brown-selected, and connect data table for instance subset.

**Comment by BlazZupan** [comment]
Also, remove combo for choosing the attribute on which to match data subset with the set of points shown. Match by data instance id only (like in other Orange widgets).

**Comment by kernc** [comment]
Please try again. Note that the selection must be made on Data that comes out of Network From Distances because the Distances changes data ids (will be solved separately elsewhere).
screenshot - 12162016 - 12 23 59 pm

**Comment by ajdapretnar** [comment]
Fixes the problem, but one minor issue remains. Report doesn't include the graph (it's empty). However, *Save Image* works nicely, so either way I'm happy to merge as it fixes the imminent problem.

**Comment by kernc** [comment]
The image issue is related to https://github.com/biolab/orange3/pull/1553.

**Pull request merged**
