### PR TITLE
[ENH] Network Explorer: add legend

### PR DESCRIPTION
**Pull request by jerneju**
##### Issue
See #16 :

> 1.) Network Explorer should display legend if coloring by attribute.

##### Includes
- [X] Code changes
- [ ] Tests
- [ ] Documentation

### CODE REVIEW

**Comment by kernc** [comment]
Default legend position (center of graphicsview) not ok.

**Comment by jerneju** [comment]
@kernc : Now its default position is top right corner. Same as in **Scatter Plot** widget.

**Comment by ajdapretnar** [comment]
I like it.

**Comment by kernc** [comment]
The legend is an item of the scene, it pans when the scene is zoomed. Instead, it should hover in a fixed position above the view.

**Comment by kernc** [comment]
Connect _Network File_ to _Network Explorer_, select Color attribute. Disconnect the connection, _Explorer_ clears. Reconnect the same connection, _Explorer_ crashes with:
```py
Traceback (most recent call last):
  File "/home/user/orange3/Orange/canvas/scheme/widgetsscheme.py", line 832, in process_signals_for_widget
    handler(*args)
  File "/home/user/orange3/networks/orangecontrib/network/widgets/OWNxExplorer.py", line 520, in set_graph
    self._set_combos()
  File "/home/user/orange3/networks/orangecontrib/network/widgets/OWNxExplorer.py", line 439, in _set_combos
    self.set_node_colors()
  File "/home/user/orange3/networks/orangecontrib/network/widgets/OWNxExplorer.py", line 626, in set_node_colors
    self.view.scene().removeItem(self.view.legend)
RuntimeError: wrapped C/C++ object of type LegendItem has been deleted
```

**Comment by jerneju** [comment]
Thanks. Fixed!

**Pull request merged**
