### PR TITLE
Network explorer 2

### PR DESCRIPTION
**Pull request by janezd**
Network Explorer was not derived from the common projection base classes and lacked many useful features, like, for instance, grouped selections. Now it is and does.

Still missing:
- manual positioning of nodes,
- widget simplifies the visualization during optimization of large graphs, such as not drawing labels and edges. The sizes at which a certain property is disabled is set ad-hoc, without any benchmarking.
- parameters of optimization (sampling, refresh rate...) are also set ad-hoc.

Also missing:
- tests,
- documentation.

##### Includes
- [X] Code changes
- [ ] Tests
- [ ] Documentation

### CODE REVIEW

**Comment by ajdapretnar** [comment]
I really really _really_ like this. I can see how Network is gonna become kickass!
A couple of small comments:
- OCD 1: There is a mysterious dot at the beginning of the selection box. 🔍 
- OCD 2: Info box and Selection box are not aligned. It is killing me. 😱 
- Does Edge width do anything, when Scale widths to weights is selected? If not, grey it out.
- Does Show weights do anything?
- Semi-OCD: I don't like how small the text edit box can get. See image below. It should not wrap so tightly around the text.

screen shot 2018-10-09 at 14 43 52

**Comment by ajdapretnar** [comment]
I have played around with airtraffic data, had many options selected, something that displays the legend. Then I changed the data to leu_by_genesets. The old legend remained.

**Comment by ajdapretnar** [comment]
Use airtraffic data and _Mark nodes whose labels start with_, say M, mark the nodes, then change the dataset. Error appears.

**Comment by janezd** [comment]
> OCD 1: There is a mysterious dot at the beginning of the selection box. 🔍

Fixed.

> OCD 2: Info box and Selection box are not aligned. It is killing me. 😱

Solved by moving this to the bottom. It's better; before that, it looked as if the whole point of the widget was marking. (Except if it actually is?)

> Does Edge width do anything, when Scale widths to weights is selected? If not, grey it out.

Now it does do something, but the check boxes are greyed out if all weights are same.

> Does Show weights do anything?

Trying to find a fast solution, though I'm not sure it exists.

> Semi-OCD: I don't like how small the text edit box can get. See image below. It should not wrap so tightly around the text.

I set a minimal width.

> Then I changed the data to leu_by_genesets. The old legend remained.

I can't replicate this. Can you?

> Use airtraffic data and Mark nodes whose labels start with, say M, mark the nodes, then change the dataset. Error appears.

Fixed.

**Comment by ajdapretnar** [comment]
All fixes are great. I just can't see the one where you moved marking to the bottom. Am I missing something?

**Comment by ajdapretnar** [comment]
Sorry for this last minute idea. But Overlap in the context of Networks really makes no sense, does it? Probably we should remove it.

**Comment by janezd** [comment]
I totally agree overlaps make no sense in this context.

On Friday, we will decide whether and where to keep the overlay, and in what form. It definitely should not appear in networks and MDS. We could keep it in the scatter plot, but replace it with different-sized pie charts (yay!) for representing class distributions. Perhaps we could also keep it in radviz, freeviz and linear projection, though I'm not too fond of it.

**Comment by ajdapretnar** [comment]
I think the main widgets that benefit from Overlap are Scatter Plot and Geo Map. The rest is very optional, meaning I'm not to fond of the idea either.

**Pull request merged**
