### PR TITLE
Output unselected subgraph in Explorer

### PR DESCRIPTION
**Pull request by kernc**
A proposed fix for https://github.com/biolab/orange3-network/issues/12.

### CODE REVIEW

**Comment by ajdapretnar** [comment]
I appreciate the new feature, but this is not exactly practical. One has to then connect another widget and set the link, etc. It's a bit of a pain. Gephi has that nicely sorted with a simple right click, but I personally vote for 'delete' button to remove the node. Then you would probably have to be able to undo with ctrl-z, too.

Also, there's an issue with exporting images.
networkkkkkk

**Comment by ajdapretnar** [comment]
This is .png, .svg has even bigger issues.

**Comment by kernc** [comment]
> this is not exactly practical

But is functional, data-flow style, it works, the 10-line change is easy to maintain and reason about, and will be easier to extend with saved selection state, whenever one gets to it.

**Comment by ajdapretnar** [comment]
Is merging your own PRs normal?

**Pull request merged**
