### PR TITLE
[FIX] File: filename check

### PR DESCRIPTION
**Pull request by jerneju**
Checking if `QFileDialog` returns `filename` sometimes causes an exception somewhere in the code.

Also add issue and pull request templates.

### CODE REVIEW

**Comment by jerneju** [comment]
https://sentry.io/biolab/orange3-network/issues/422770092/

**Comment by kernc** [comment]
I don't understand how this was supposed to fix anything. If `getOpenFileName` returns `filename` string, why check `filename[0]`? How can `filename and filename[0]` ever fail at the second condition?

**Comment by jerneju** [comment]
@kernc : `getOpenFileName` returns a `tuple` not a string. 

`('', '')` can fail at the second condition.

However now it is fixed in another way.

**Comment by jerneju** [comment]
https://sentry.io/biolab/orange3-network/issues/420029505/

**Comment by jerneju** [comment]
https://sentry.io/biolab/orange3-network/issues/425314466/

**Pull request merged**
