### PR TITLE
[ENH] Improve Fruchterman-Reingold implementation

### LINKED ISSUE #182: Remove Cythonized files
We should probably remove C++ files, built by Cython, like in core Orange?

Any help with build scripts appreciated.

### PR DESCRIPTION
**Pull request by janezd**
##### Issue

Drawn networks are not nice. Primarily because only 10% of vertices were sampled for repulsive forces.

Also fixes  #182

#### Changes visible to the user

- sample all vertices, unless there are more than 1000, in which case sample 1000 / #number of vertices,
- draw all edges during optimization, because it's fast enough and looks nice,
- better annealing schedule,
- instead of setting the number of iterations, set the aloted time (aims for 30s, but always finishes earlier); first run 20 iterations of the algorithm to measure time, then compute the allowed number of iterations (needed in advance to set the annealing),
- speed improvements (relatively: optimization is set to take longer, but each iteration is about 3 times faster, so the end result should improve),
- more sensible UX for reset from random positions,
- an option to disable taking edge weights into account,
- slider for setting the gravity, which allows for better layouts for graphs with many disconnected smaller components,

#### Fixes
- fixed progress bar.
- fixed  annealing that was computed per component instead of per entire vector, which caused jittering at the end of optimization
 
#### Invisible code changes
- the main loop moved from Cython to Python, for easier control,
- split Cython code into functions,
- remove cythonized file from git,
- remove the half-supported multidimensional layouts; unroll the loops (which only took two iterations)
- optimized computation: 
    - avoid square roots for repulsive forces,
    - multiply with pre-computed inverses instead of dividing,
    - halve the computation of repulsive forces by updating both nodes at the same time

##### Includes
- [X] Code changes
- [ ] Tests
- [ ] Documentation

### CODE REVIEW

**Comment by janezd** [comment]
I returned this to draft status. I realized that the outer loop in Cython could easily be in Python because it executes only a few thousand times and the core complexity is inside of it. We only need to prepare this beforehand:

```
        disp = np.empty((pos.shape[0], pos.shape[1]))
        delta = np.empty(pos.shape[1])
        sample_size = max(int(round(n_nodes*sample_ratio)), 1)
        sample = np.zeros(sample_size, dtype=np.int32)
```

This would simplify the code a lot.

Besides, the first function in Cython, `fruchterman_reingold_layout` is unused, useless and contains no code that couldn't be in Python.

**Comment by ajdapretnar** [comment]
> fixup! FR: 3-times speed-up
😮 🎉

**Comment by janezd** [comment]
> > fixup! FR: 3-times speed-up
> 
> 😮 🎉

Heh, thanks.

**Comment by janezd** [comment]
Yes, for both questions. I'm avoiding memory lookups or conditional jumps.

**Comment by thocevar** [comment]
- In my case it crashes on almost every dataset (e.g. `airtraffic`) except `lastfm`, which is the largest. This one, however, takes about a minute to complete.

```
orange3-network\orangecontrib\network\network\layout\__init__.py", line 57, in fruchterman_reingold
    iterations = int(allowed_time / (elapsed_time / TEST_ITERATIONS))
ZeroDivisionError: float division by zero
```

- Current implementation is pretty fast at least for the example datasets. Is it just the parameters or did you time the execution of single iteration? 
- Does avoiding branches by duplicating code really help? Did you measure this? The compilers are usually pretty smart and it's hard to make a significant difference with such manual tweaks.
- Changing parameters during optimization crashes entire application.
- Changing gravity automatically restarts optimization, which usually leads to a crash for the previous reason as you click again to change gravity further.

**Comment by janezd** [comment]
- All crash with division by zero? This means that `elapsed_time` is zero? Could you please investigate? It works for me.
- Current implementation aims to run for 30 seconds. Running for 1 minute may happen because of bad time measurement.
- Speed: I compared the number of iterations in 10 seconds. The new implementation is about three times faster.
- I haven't measured the effect of branching. I however can't imagine what could a compiler do here. Splitting the function into two has no effect, if branching is inexpensive. Though, I also like separated functions for simplicity (although it duplicated code).
- Crashing when changing parameters (or inputing a new network) during optimization: this is unrelated to this change and I'm opening this as a separate issue. Threads are not implemented as they should be.

**Comment by thocevar** [comment]
Using `time.process_time` results in 0 elapsed time. I found this [blog](https://www.webucator.com/blog/2015/08/python-clocks-explained/) that encounters similar low resolution problems with `process_time`. Works fine with `time.perf_counter`. Documentation (https://docs.python.org/3/library/time.html#time.perf_counter) says that it should have the highest resolution. However, it is system-wide, which is actually another plus because the user only cares about the actual time until completion. This also solves the 1 minute problem. However, there is significant slow-down if you open the widget, which has to visualize the movement of nodes. Closing it speeds up the process.

Ok, I guess having two separate functions doesn't hurt, although I would guess it doesn't help much either, but am too lazy to check.

I like the slider for gravity. It's hard to come up with the right default value for all cases. Maybe we can expose some other constant as well?

Do you have any examples of previously bad visualizations for comparison? I don't remember them as particularly bad.

**Comment by janezd** [comment]
I merged `attract` and `attract_weighted`. It didn't seem to affect the speed. I haven't profiled FR, but I suppose that the slower part are computation of repulsive forces (quadratic with number of vertices, while attract is linear with edges, which is typically less). I would not merge `repulse`.

I replaced `process_time` with `perf_counter`. It overshoots (lastfm took 45 s instead of 30 s), but I don't mind because the layout was still improving.

We can expose `k`, but gravity has a similar effect. The other parameters are initial and final temperature and time. I'd keep them hardcoded. Users can click improve for as long as they want.

My comment about ugly layouts refered to local neighbourhoods. Network as whole could be OK, but if you zoomed it in, the local layout was ugly. I observed this on Last FM. I have a feeling it's better now, though I'm not sure. The changes that could affect the layout are: more iterations, better gravity (per-dimension instead of spherical, also resulting in the network feeling the rectangular area), quadratic annealing schedule and fixed bug in treatment of temperature.

**Pull request merged**
